export const bookImages = {
    "Carrie": "/images/bookCoversCards/carrie.png",
    "11/22/63": "/images/bookCoversCards/11-22-63.png",
    "Bag of Bones": "/images/bookCoversCards/bagOfBones.png",
    "Black House": "/images/bookCoversCards/blackHouse.png",
    "Blaze": "/images/bookCoversCards/blaze.png",
    "Billy Summers": "/images/bookCoversCards/billySummers.png",
    "Cell": "/images/bookCoversCards/cell.png",
    "Christine": "/images/bookCoversCards/christine.png",
    "Cujo": "/images/bookCoversCards/cujo.png",
    "Cycle of the Werewolf": "/images/bookCoversCards/cycleOfTheWerewolf.png",
    "Desperation": "/images/bookCoversCards/desperation.png",
    "Doctor Sleep": "/images/bookCoversCards/doctorSleep.png",
    "Dolores Claiborne": "/images/bookCoversCards/doloresClaiborne.png",
    "Dreamcatcher": "/images/bookCoversCards/dreamcatcher.png",
    "Duma Key": "/images/bookCoversCards/dumaKey.png",
    "Elevation": "/images/bookCoversCards/elevation.png",
    "End of Watch": "/images/bookCoversCards/endOfWatch.png",
    "Firestarter": "/images/bookCoversCards/firestarter.png",
    "Finders Keepers": "/images/bookCoversCards/findersKeepers.png",
    "From a Buick 8": "/images/bookCoversCards/fromABuick8.png",
    "Gerald's Game": "/images/bookCoversCards/geralsGame.png",
    "Gwendy's Button Box": "/images/bookCoversCards/gwendysButtonBox.png",
    "Hearts in Atlantis": "/images/bookCoversCards/heartsInAtlantis.png",
    "Insomnia": "/images/bookCoversCards/insomnia.png",
    "It": "/images/bookCoversCards/it.png",
    "Joyland": "/images/bookCoversCards/joyland.png",
    "Later": "/images/bookCoversCards/later.png",
    "Lisey's Story": "/images/bookCoversCards/liseysStory.png",
    "Misery": "/images/bookCoversCards/misery.png",
    "Mr. Mercedes": "/images/bookCoversCards/mrMercedes.png",
    "Needful Things": "/images/bookCoversCards/needfulThings.png",
    "Night Shift": "/images/bookCoversCards/nightShift.png",
    "Pet Sematary": "/images/bookCoversCards/petSematary.png",
    "Rage": "/images/bookCoversCards/rage.png",
    "Revival": "/images/bookCoversCards/revival.png",
    "Roadwork": "/images/bookCoversCards/roadwork.png",
    "Rose Madder": "/images/bookCoversCards/roseMadder.png",
    "Salem's Lot": "/images/bookCoversCards/salemsLot.png",
    "Sleeping Beauties": "/images/bookCoversCards/sleepingBeauties.png",
    "The Colorado Kid": "/images/bookCoversCards/theColoradoKid.png",
    "The Dark Half": "/images/bookCoversCards/theDarkHalf.png",
    "The Dark Tower: The Gunslinger": "/images/bookCoversCards/theDarkTower.png",
    "The Dark Tower II: The Drawing of the Three": "/images/bookCoversCards/theDarkTowerTheDrawingOfTheThree.png",
    "The Dark Tower III: The Waste Lands": "/images/bookCoversCards/theDarkTowerTheWasteLands.png",
    "The Dark Tower V: Wolves of the Calla": "/images/bookCoversCards/theDarkTowerWolvesOfTheCalla.png",
    "The Dark Tower VI: Song of Susannah": "/images/bookCoversCards/theDarkTowerSongOfSusannah.png",
    "The Dark Tower IV: Wizard and Glass": "/images/bookCoversCards/theDarkTowerWizardAndGlass.png",
    "The Dark Tower VII: The Dark Tower": "/images/bookCoversCards/theDarkTowerTheDarkTower.png",
    "The Dark Tower: The Wind Through the Keyhole": "/images/bookCoversCards/theDarkTowerTheWindThroughTheKeyhole.png",
    "The Dead Zone": "/images/bookCoversCards/theDeadZone.png",
    "The Eyes of the Dragon": "/images/bookCoversCards/theEyesOfTheDragon.png",
    "The Girl Who Loved Tom Gordon": "/images/bookCoversCards/theGirlWhoLovedTomGordon.png",
    "The Green Mile": "/images/bookCoversCards/theGreenMile.png",
    "The Institute": "/images/bookCoversCards/theInstitute.png",
    "The Long Walk": "/images/bookCoversCards/theLongWalk.png",
    "The Outsider": "/images/bookCoversCards/theOutsider.png",
    "The Regulators": "/images/bookCoversCards/theRegulators.png",
    "The Running Man": "/images/bookCoversCards/theRunningMan.png",
    "The Shining": "/images/bookCoversCards/theShining.png",
    "The Stand": "/images/bookCoversCards/theStand.png",
    "The Stand Uncut": "/images/bookCoversCards/theStandUncut.png",
    "The Talisman": "/images/bookCoversCards/theTalisman.png",
    "The Tommyknockers": "/images/bookCoversCards/theTommyknockers.png",
    "Thinner": "/images/bookCoversCards/thinner.png",
    "Under the Dome": "/images/bookCoversCards/underTheDome.png",
    
    };

export const getBookImage = (title) => {
return bookImages[title] || "/images/bookCoversCards/default.png";
};