export const bookImages = {
    "Carrie": "public/images/bookCoversCards/carrie.png",
    "11/22/63": "public/images/bookCoversCards/112263.png",
    "Bag of Bones": "public/images/bookCoversCards/bagOfBones.png",
    "Black House": "public/images/bookCoversCards/blackHouse.png",
    "Christine": "public/images/bookCoversCards/christine.png",
    "Cujo": "public/images/bookCoversCards/cujo.png",
    "Cycle of the Werewolf": "public/images/bookCoversCards/cycleOfTheWerewolf.png",
    "Doctor Sleep": "public/images/bookCoversCards/doctorSleep.png",
    "Dolores Claiborne": "public/images/bookCoversCards/doloresClaiborne.png",
    "Dreamcatcher": "public/images/bookCoversCards/dreamcatcher.png",
    "Firestarter": "public/images/bookCoversCards/firestarter.png",
    "From a Buick 8": "public/images/bookCoversCards/fromABuick8.png",
    "Gerald's Game": "public/images/bookCoversCards/geralsGame.png",
    "Hearts in Atlantis": "public/images/bookCoversCards/heartsInAtlantis.png",
    "Insomnia": "public/images/bookCoversCards/insomnia.png",
    "It": "public/images/bookCoversCards/it.png",
    "Lisey's Story": "public/images/bookCoversCards/liseysStory.png",
    "Misery": "public/images/bookCoversCards/misery.png",
    "Needful Things": "public/images/bookCoversCards/needfulThings.png",
    "Night Shift": "public/images/bookCoversCards/nightShift.png",
    "Pet Sematary": "public/images/bookCoversCards/petSematary.png",
    "Rage": "public/images/bookCoversCards/rage.png",
    "Revival": "public/images/bookCoversCards/revival.png",
    "Roadwork": "public/images/bookCoversCards/roadwork.png",
    "Rose Madder": "public/images/bookCoversCards/roseMadder.png",
    "Salem's Lot": "public/images/bookCoversCards/salemsLot.png",
    "The Dark Half": "public/images/bookCoversCards/theDarkHalf.png",
    "The Dark Tower: The Gunslinger": "public/images/bookCoversCards/theDarkTowerTheGunslinger.png",
    "The Dark Tower V: Wolves of the Calla": "public/images/bookCoversCards/theDarkTowerWolvesOfTheCalla.png",
    "The Dark Tower IV: Wizard and Glass": "public/images/bookCoversCards/theDarkTowerWizardAndGlass.png",
    "The Dead Zone": "public/images/bookCoversCards/theDeadZone.png",
    "The Girl Who Loved Tom Gordon": "public/images/bookCoversCards/theGirlWhoLovedTomGordon.png",
    "The Green Mile": "public/images/bookCoversCards/theGreenMile.png",
    "The Long Walk": "public/images/bookCoversCards/theLongWalk.png",
    "The Outsider": "public/images/bookCoversCards/theOutsider.png",
    "The Regulators": "public/images/bookCoversCards/theRegulators.png",
    "The Running Man": "public/images/bookCoversCards/theRunningMan.png",
    "The Shining": "public/images/bookCoversCards/theShining.png",
    "The Stand": "public/images/bookCoversCards/theStand.png",
    "The Talisman": "public/images/bookCoversCards/theTalisman.png",
    "The Tommyknockers": "public/images/bookCoversCards/theTommyknockers.png",
    "Thinner": "public/images/bookCoversCards/thinner.png",
    "Under the Dome": "public/images/bookCoversCards/underTheDome.png",
    
    };

export const getBookImage = (title) => {
return bookImages[title] || "public/images/bookCoversCards/default.png";
};