export const bookImages = {
    "Carrie": "public/images/bookCoversCards/carrie.png",
    "11/22/63": "public/images/bookCoversCards/11-22-63.png",
    "Bag of Bones": "public/images/bookCoversCards/bagOfBones.png",
    "Black House": "public/images/bookCoversCards/blackHouse.png",
    "Blaze": "public/images/bookCoversCards/blaze.png",
    "Billy Summers": "public/images/bookCoversCards/billySummers.png",
    "Cell": "public/images/bookCoversCards/cell.png",
    "Christine": "public/images/bookCoversCards/christine.png",
    "Cujo": "public/images/bookCoversCards/cujo.png",
    "Cycle of the Werewolf": "public/images/bookCoversCards/cycleOfTheWerewolf.png",
    "Desperation": "public/images/bookCoversCards/desperation.png",
    "Doctor Sleep": "public/images/bookCoversCards/doctorSleep.png",
    "Dolores Claiborne": "public/images/bookCoversCards/doloresClaiborne.png",
    "Dreamcatcher": "public/images/bookCoversCards/dreamcatcher.png",
    "Duma Key": "public/images/bookCoversCards/dumaKey.png",
    "Elevation": "public/images/bookCoversCards/elevation.png",
    "End of Watch": "public/images/bookCoversCards/endOfWatch.png",
    "Firestarter": "public/images/bookCoversCards/firestarter.png",
    "Finders Keepers": "public/images/bookCoversCards/findersKeepers.png",
    "From a Buick 8": "public/images/bookCoversCards/fromABuick8.png",
    "Gerald's Game": "public/images/bookCoversCards/geralsGame.png",
    "Gwendy's Button Box": "public/images/bookCoversCards/gwendysButtonBox.png",
    "Hearts in Atlantis": "public/images/bookCoversCards/heartsInAtlantis.png",
    "Insomnia": "public/images/bookCoversCards/insomnia.png",
    "It": "public/images/bookCoversCards/it.png",
    "Joyland": "public/images/bookCoversCards/joyland.png",
    "Later": "public/images/bookCoversCards/later.png",
    "Lisey's Story": "public/images/bookCoversCards/liseysStory.png",
    "Misery": "public/images/bookCoversCards/misery.png",
    "Mr. Mercedes": "public/images/bookCoversCards/mrMercedes.png",
    "Needful Things": "public/images/bookCoversCards/needfulThings.png",
    "Night Shift": "public/images/bookCoversCards/nightShift.png",
    "Pet Sematary": "public/images/bookCoversCards/petSematary.png",
    "Rage": "public/images/bookCoversCards/rage.png",
    "Revival": "public/images/bookCoversCards/revival.png",
    "Roadwork": "public/images/bookCoversCards/roadwork.png",
    "Rose Madder": "public/images/bookCoversCards/roseMadder.png",
    "Salem's Lot": "public/images/bookCoversCards/salemsLot.png",
    "Sleeping Beauties": "public/images/bookCoversCards/sleepingBeauties.png",
    "The Colorado Kid": "public/images/bookCoversCards/theColoradoKid.png",
    "The Dark Half": "public/images/bookCoversCards/theDarkHalf.png",
    "The Dark Tower: The Gunslinger": "public/images/bookCoversCards/theDarkTower.png",
    "The Dark Tower II: The Drawing of the Three": "public/images/bookCoversCards/theDarkTowerTheDrawingOfTheThree.png",
    "The Dark Tower III: The Waste Lands": "public/images/bookCoversCards/theDarkTowerTheWasteLands.png",
    "The Dark Tower V: Wolves of the Calla": "public/images/bookCoversCards/theDarkTowerWolvesOfTheCalla.png",
    "The Dark Tower VI: Song of Susannah": "public/images/bookCoversCards/theDarkTowerSongOfSusannah.png",
    "The Dark Tower IV: Wizard and Glass": "public/images/bookCoversCards/theDarkTowerWizardAndGlass.png",
    "The Dark Tower VII: The Dark Tower": "public/images/bookCoversCards/theDarkTowerTheDarkTower.png",
    "The Dark Tower: The Wind Through the Keyhole": "public/images/bookCoversCards/theDarkTowerTheWindThroughTheKeyhole.png",
    "The Dead Zone": "public/images/bookCoversCards/theDeadZone.png",
    "The Eyes of the Dragon": "public/images/bookCoversCards/theEyesOfTheDragon.png",
    "The Girl Who Loved Tom Gordon": "public/images/bookCoversCards/theGirlWhoLovedTomGordon.png",
    "The Green Mile": "public/images/bookCoversCards/theGreenMile.png",
    "The Institute": "public/images/bookCoversCards/theInstitute.png",
    "The Long Walk": "public/images/bookCoversCards/theLongWalk.png",
    "The Outsider": "public/images/bookCoversCards/theOutsider.png",
    "The Regulators": "public/images/bookCoversCards/theRegulators.png",
    "The Running Man": "public/images/bookCoversCards/theRunningMan.png",
    "The Shining": "public/images/bookCoversCards/theShining.png",
    "The Stand": "public/images/bookCoversCards/theStand.png",
    "The Stand Uncut": "public/images/bookCoversCards/theStandUncut.png",
    "The Talisman": "public/images/bookCoversCards/theTalisman.png",
    "The Tommyknockers": "public/images/bookCoversCards/theTommyknockers.png",
    "Thinner": "public/images/bookCoversCards/thinner.png",
    "Under the Dome": "public/images/bookCoversCards/underTheDome.png",
    
    };

export const getBookImage = (title) => {
return bookImages[title] || "public/images/bookCoversCards/default.png";
};